//! Offline reverse geocoding -- the `mma-geocode` crate over the packed GeoNames table
//! `data/cities.bin` (generated by `scripts/gen-cities-bin.mjs`).

use mma_geocode::Geocoder;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

#[repr(align(4))]
struct Aligned<B: ?Sized>(B);
static TABLE: &Aligned<[u8]> = &Aligned(*include_bytes!("../../data/cities.bin"));

fn geocoder() -> &'static Geocoder<'static> {
    static GEOCODER: OnceLock<Geocoder<'static>> = OnceLock::new();
    GEOCODER.get_or_init(|| Geocoder::new(&TABLE.0).expect("cities.bin: invalid table"))
}

/// Reverse geocode result: nearest populated place to a coordinate.
#[derive(Serialize, specta::Type)]
pub struct GeoResult {
    pub city: String,
    /// First-level administrative division (state, province, region).
    pub admin: String,
    /// ISO 3166-1 alpha-2 (e.g. "US", "FR").
    pub country_code: String,
    pub country: String,
    pub province: String,
    pub district: String,
    pub town: String,
    pub adcode: String,
    pub formatted_address: String,
}

/// Validate the table's header ahead of the first lookup.
pub fn warm() {
    geocoder();
}

/// Return the nearest city, administrative region, and country for a coordinate.
/// Never `null`: every landmass is covered.
#[tauri::command]
#[specta::specta]
pub fn reverse_geocode(lat: f64, lng: f64, source: Option<String>) -> Option<GeoResult> {
    let china = matches!(
        source.as_deref(),
        Some("baidu_pano" | "qq_pano" | "qq_trekker")
    );
    if china {
        if let Some(result) = baidu_reverse_geocode(lat, lng) {
            return Some(result);
        }
    }
    let (lat, lng) = if china {
        gcj_to_wgs(lat, lng)
    } else {
        (lat, lng)
    };
    geocoder().nearest(lat, lng).map(|r| GeoResult {
        city: r.name,
        admin: r.admin1.to_string(),
        country_code: r.country_code.to_string(),
        country: r.country_code.to_string(),
        province: r.admin1.to_string(),
        district: String::new(),
        town: String::new(),
        adcode: String::new(),
        formatted_address: String::new(),
    })
}

// Provider coordinates stay GCJ-02; the offline GeoNames table uses WGS84.
fn gcj_to_wgs(lat: f64, lng: f64) -> (f64, f64) {
    if !(72.004..=137.8347).contains(&lng) || !(0.8293..=55.8271).contains(&lat) {
        return (lat, lng);
    }
    let x = lng - 105.0;
    let y = lat - 35.0;
    let pi = std::f64::consts::PI;
    let common = (20.0 * (6.0 * x * pi).sin() + 20.0 * (2.0 * x * pi).sin()) * 2.0 / 3.0;
    let dlat = -100.0
        + 2.0 * x
        + 3.0 * y
        + 0.2 * y * y
        + 0.1 * x * y
        + 0.2 * x.abs().sqrt()
        + common
        + (20.0 * (y * pi).sin() + 40.0 * (y * pi / 3.0).sin()) * 2.0 / 3.0
        + (160.0 * (y * pi / 12.0).sin() + 320.0 * (y * pi / 30.0).sin()) * 2.0 / 3.0;
    let dlng = 300.0
        + x
        + 2.0 * y
        + 0.1 * x * x
        + 0.1 * x * y
        + 0.1 * x.abs().sqrt()
        + common
        + (20.0 * (x * pi).sin() + 40.0 * (x * pi / 3.0).sin()) * 2.0 / 3.0
        + (150.0 * (x * pi / 12.0).sin() + 300.0 * (x * pi / 30.0).sin()) * 2.0 / 3.0;
    let rad = lat.to_radians();
    let magic = 1.0 - 0.00669342162296594323 * rad.sin().powi(2);
    (
        lat - dlat * 180.0 / ((6335552.717000426 / magic.powf(1.5)) * pi),
        lng - dlng * 180.0 / ((6378245.0 / magic.sqrt()) * rad.cos() * pi),
    )
}

#[cfg(test)]
mod china_coordinates {
    #[test]
    fn offline_boundary_removes_china_offset_only_inside_china() {
        let (lat, lng) = super::gcj_to_wgs(39.910226, 116.403714);
        assert!((lat - 39.908823).abs() < 0.00002);
        assert!((lng - 116.39747).abs() < 0.00002);
        assert_eq!(super::gcj_to_wgs(48.8566, 2.3522), (48.8566, 2.3522));
    }
}

#[derive(Default, Deserialize)]
struct BaiduAddressComponent {
    #[serde(default)]
    province: String,
    #[serde(default)]
    city: String,
    #[serde(default)]
    district: String,
    #[serde(default)]
    town: String,
    #[serde(default)]
    adcode: String,
}

#[derive(Deserialize)]
struct BaiduReverseResult {
    #[serde(rename = "addressComponent", alias = "address_component", default)]
    address_component: BaiduAddressComponent,
    #[serde(default)]
    formatted_address: String,
}

#[derive(Deserialize)]
struct BaiduReverseResponse {
    status: i32,
    result: Option<BaiduReverseResult>,
}

fn baidu_reverse_geocode(lat: f64, lng: f64) -> Option<GeoResult> {
    if !(72.0..=138.0).contains(&lng) || !(0.0..=56.0).contains(&lat) {
        return None;
    }
    let ak = std::env::var("MMA_BAIDU_REVERSE_AK").ok()?;
    let url = format!(
        "https://api.map.baidu.com/reverse_geocoding/v3/?ak={ak}&location={lat},{lng}&coordtype=gcj02ll&output=json&radius=100&page_size=10&extensions_poi=0&res=webmap&pcevaname=pc4.1&newfrom=zhuzhan_webmap"
    );
    let response = crate::net::proxy::proxy_client()
        .get(url)
        .header("Referer", "https://map.baidu.com/")
        .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/114.0.0.0 Safari/537.36")

        .header("Accept", "application/json")
        .send()
        .ok()?
        .error_for_status()
        .ok()?;
    let data: BaiduReverseResponse = response.json().ok()?;
    if data.status != 0 {
        log::warn!(
            "[geocode] Baidu reverse geocode returned status {}",
            data.status
        );
        return None;
    }
    let result = data.result?;
    let c = result.address_component;
    let city = c.city.clone();
    let admin = if !c.province.is_empty() {
        c.province.clone()
    } else {
        city.clone()
    };
    Some(GeoResult {
        city,
        admin,
        country: "中国".into(),
        country_code: "CN".into(),
        province: c.province,
        district: c.district,
        town: c.town,
        adcode: c.adcode,
        formatted_address: result.formatted_address,
    })
}
